// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using long_term_care.Models;

namespace long_term_care.Migrations
{
    [DbContext(typeof(longtermcareContext))]
    [Migration("20230629064911_CreateRolesTable")]
    partial class CreateRolesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("long_term_care.Models.CarPick", b =>
                {
                    b.Property<string>("CarId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Car_ID");

                    b.Property<string>("CarAgencyLoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Car_AgencyLoc");

                    b.Property<string>("CarCaseAdr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Car_CaseAdr");

                    b.Property<double>("CarKm")
                        .HasColumnType("float")
                        .HasColumnName("Car_Km");

                    b.Property<double>("CarL")
                        .HasColumnType("float")
                        .HasColumnName("Car_L");

                    b.Property<DateTime>("CarMonth")
                        .HasColumnType("date")
                        .HasColumnName("Car_Month");

                    b.Property<string>("CarNum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Car_Num");

                    b.Property<decimal>("CarPrice")
                        .HasColumnType("money")
                        .HasColumnName("Car_Price");

                    b.Property<DateTime>("CarSearch")
                        .HasColumnType("datetime")
                        .HasColumnName("Car_Search");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Car_Type");

                    b.Property<string>("CaseNo")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.Property<string>("MemSid")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SID");

                    b.HasKey("CarId")
                        .HasName("PK__car_pick__523653D98367FCC5");

                    b.HasIndex("MemSid");

                    b.ToTable("car_pick");
                });

            modelBuilder.Entity("long_term_care.Models.CaseAct", b =>
                {
                    b.Property<string>("ActId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Act_ID");

                    b.Property<string>("ActCourse")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Act_Course");

                    b.Property<DateTime>("ActDate")
                        .HasColumnType("date")
                        .HasColumnName("Act_Date");

                    b.Property<string>("ActLec")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Act_Lec");

                    b.Property<string>("ActLoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Act_Loc");

                    b.HasKey("ActId")
                        .HasName("PK__case_act__6564ADDDE6E88FEE");

                    b.ToTable("case_act");
                });

            modelBuilder.Entity("long_term_care.Models.CaseActContent", b =>
                {
                    b.Property<string>("ActId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Act_ID");

                    b.Property<string>("CaseNo")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.Property<string>("ActSer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Act_Ser");

                    b.HasKey("ActId", "CaseNo")
                        .HasName("PK__Case_Act__5862BDFE9B8D3FC1");

                    b.HasIndex("CaseNo");

                    b.ToTable("Case_Act_Content");
                });

            modelBuilder.Entity("long_term_care.Models.CaseCareRecord", b =>
                {
                    b.Property<string>("CaseQaid")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_QAID");

                    b.Property<string>("CaseHealth")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Case_Health");

                    b.Property<string>("CaseHome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Case_Home");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.Property<string>("CaseQ1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_q1");

                    b.Property<string>("CaseQ1Other")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_q1_other");

                    b.Property<string>("CaseQ2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_q2");

                    b.Property<string>("CaseQ2Other")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_q2_other");

                    b.Property<string>("CaseQ3")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_q3");

                    b.Property<string>("CaseQ3Other")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_q3_other");

                    b.Property<string>("CaseQ4")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_q4");

                    b.Property<string>("CaseQ4Other")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_q4_other");

                    b.Property<string>("CaseTel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Case_Tel");

                    b.Property<DateTime>("CaseTime1")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_Time1");

                    b.Property<string>("MemSid")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SID");

                    b.HasKey("CaseQaid")
                        .HasName("PK__Case_Car__21B54A279265BE84");

                    b.HasIndex("CaseNo");

                    b.HasIndex("MemSid");

                    b.ToTable("Case_Care_Records");
                });

            modelBuilder.Entity("long_term_care.Models.CaseDailyRegistration", b =>
                {
                    b.Property<string>("CaseContId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_ContID");

                    b.Property<string>("CaseBlood")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Blood");

                    b.Property<string>("CaseDiastolic")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Diastolic");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.Property<string>("CasePick")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Case_Pick");

                    b.Property<string>("CasePluse")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Pluse");

                    b.Property<string>("CaseSystolic")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Systolic");

                    b.Property<string>("CaseTemp")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Temp");

                    b.Property<DateTime>("Casedate")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_date");

                    b.HasKey("CaseContId")
                        .HasName("PK__case_dai__0D7D6BC7A01B2B94");

                    b.HasIndex("CaseNo");

                    b.ToTable("case_daily_registration");
                });

            modelBuilder.Entity("long_term_care.Models.CaseInfor", b =>
                {
                    b.Property<string>("CaseNo")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.Property<string>("CaseActv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Actv");

                    b.Property<string>("CaseAddr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Addr");

                    b.Property<string>("CaseBd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_BD");

                    b.Property<string>("CaseCntAdd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_CntAdd");

                    b.Property<string>("CaseCntRel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_CntRel");

                    b.Property<string>("CaseCntTel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_CntTel");

                    b.Property<string>("CaseCnta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Cnta");

                    b.Property<string>("CaseDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Desc");

                    b.Property<string>("CaseEdu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Edu");

                    b.Property<string>("CaseFactly")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Factly");

                    b.Property<string>("CaseFami")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Fami");

                    b.Property<string>("CaseFund")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Fund");

                    b.Property<string>("CaseGender")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Gender");

                    b.Property<string>("CaseHealth")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Health");

                    b.Property<string>("CaseHouse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_House");

                    b.Property<string>("CaseIdcard")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Case_IDcard");

                    b.Property<string>("CaseIdent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Ident");

                    b.Property<string>("CaseLang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Lang");

                    b.Property<string>("CaseMari")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Mari");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Name");

                    b.Property<string>("CasePassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Password");

                    b.Property<string>("CaseProf")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Prof");

                    b.Property<string>("CaseQues")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Ques");

                    b.Property<string>("CaseRegName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_RegName");

                    b.Property<string>("CaseRegTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_RegTime");

                    b.Property<string>("CaseRelig")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Relig");

                    b.Property<string>("CaseSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Source");

                    b.Property<string>("CaseUnitName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Case_UnitName");

                    b.Property<string>("CaseUnitNum")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_UnitNum");

                    b.Property<string>("CaseWork")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Work");

                    b.HasKey("CaseNo")
                        .HasName("PK__case_inf__D0610232CD08B242");

                    b.ToTable("case_infor");
                });

            modelBuilder.Entity("long_term_care.Models.CaseNeed", b =>
                {
                    b.Property<string>("CaseNeedId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_NeedID");

                    b.Property<string>("CaseAct")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Act");

                    b.Property<string>("CaseCare")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Care");

                    b.Property<string>("CaseCons")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Cons");

                    b.Property<string>("CaseEat")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Eat");

                    b.Property<string>("CaseFami")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Fami");

                    b.Property<string>("CaseHear")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Hear");

                    b.Property<string>("CaseMed")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Med");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.Property<string>("CaseRead")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Read");

                    b.Property<string>("CaseSee")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_See");

                    b.Property<string>("CaseSpeak")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Speak");

                    b.Property<string>("CaseView1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View1");

                    b.Property<string>("CaseView2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View2");

                    b.Property<string>("CaseView3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View3");

                    b.Property<string>("CaseView4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View4");

                    b.Property<string>("CaseView5")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View5");

                    b.Property<string>("CaseView6")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View6");

                    b.Property<string>("CaseView7")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View7");

                    b.Property<string>("CaseView8")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View8");

                    b.Property<string>("CaseView9")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View9");

                    b.HasKey("CaseNeedId");

                    b.HasIndex("CaseNo");

                    b.ToTable("Case_Need");
                });

            modelBuilder.Entity("long_term_care.Models.CasePhysicalMental", b =>
                {
                    b.Property<string>("CaseQaid")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_QAID");

                    b.Property<string>("CaseContent1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content1");

                    b.Property<string>("CaseContent10")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content10");

                    b.Property<string>("CaseContent11")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content11");

                    b.Property<string>("CaseContent12")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content12");

                    b.Property<string>("CaseContent13")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content13");

                    b.Property<string>("CaseContent2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content2");

                    b.Property<string>("CaseContent3")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content3");

                    b.Property<string>("CaseContent4")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content4");

                    b.Property<string>("CaseContent5")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content5");

                    b.Property<string>("CaseContent6")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content6");

                    b.Property<string>("CaseContent7")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content7");

                    b.Property<string>("CaseContent8")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content8");

                    b.Property<string>("CaseContent9")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content9");

                    b.Property<string>("CaseFre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Case_Fre");

                    b.Property<string>("CaseLive")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Case_Live");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.HasKey("CaseQaid")
                        .HasName("PK__case_phy__21B54A278516737A");

                    b.HasIndex("CaseNo");

                    b.ToTable("case_physical_mental");
                });

            modelBuilder.Entity("long_term_care.Models.CaseTelRecord", b =>
                {
                    b.Property<string>("CaseTelQaid")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_TelQAID");

                    b.Property<string>("CaseAns")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Ans");

                    b.Property<string>("CaseCom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Case_Com");

                    b.Property<int>("CaseDay")
                        .HasColumnType("int");

                    b.Property<string>("CaseExp")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Exp");

                    b.Property<string>("CaseFam")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Fam");

                    b.Property<string>("CaseHea")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Hea");

                    b.Property<string>("CaseLive")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Live");

                    b.Property<string>("CaseMental")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Mental");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.Property<DateTime>("CaseRegTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_RegTime");

                    b.Property<string>("CaseSick")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Case_Sick");

                    b.Property<DateTime>("CaseTelTime1")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_TelTime1");

                    b.Property<DateTime>("CaseTelTime2")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_TelTime2");

                    b.Property<string>("MemSid")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SID");

                    b.HasKey("CaseTelQaid")
                        .HasName("PK__Case_Tel__8C289C6576F0578D");

                    b.HasIndex("CaseNo");

                    b.HasIndex("MemSid");

                    b.ToTable("Case_Tel_Records");
                });

            modelBuilder.Entity("long_term_care.Models.LectureClass", b =>
                {
                    b.Property<string>("SchWeek")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Sch_Week");

                    b.Property<string>("SchA")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Sch_A");

                    b.Property<string>("SchB")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Sch_B");

                    b.Property<string>("SchC")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Sch_C");

                    b.Property<string>("SchD")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Sch_D");

                    b.Property<string>("SchE")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Sch_E");

                    b.Property<int?>("Weeknum")
                        .HasColumnType("int")
                        .HasColumnName("weeknum");

                    b.HasKey("SchWeek")
                        .HasName("PK__lecture___CE91D8F57C0189BF");

                    b.ToTable("lecture_class");
                });

            modelBuilder.Entity("long_term_care.Models.LectureTable", b =>
                {
                    b.Property<string>("LecId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Lec_ID");

                    b.Property<string>("LecAim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Lec_Aim");

                    b.Property<string>("LecClass")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Lec_Class");

                    b.Property<DateTime>("LecDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Lec_Date");

                    b.Property<string>("LecLeader")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Lec_Leader");

                    b.Property<string>("LecPla")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Lec_Pla");

                    b.Property<string>("LecStep")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Lec_Step");

                    b.Property<string>("LecTheme")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Lec_Theme");

                    b.Property<string>("LecTool")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Lec_Tool");

                    b.Property<string>("MemSid")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SID");

                    b.HasKey("LecId")
                        .HasName("PK__lecture___2E5B8E905793C8AC");

                    b.HasIndex("MemSid");

                    b.ToTable("lecture_table");
                });

            modelBuilder.Entity("long_term_care.Models.MemSign", b =>
                {
                    b.Property<string>("MemSignQaid")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SignQAID");

                    b.Property<string>("MemRecord")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Mem_Record");

                    b.Property<string>("MemSid")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SID");

                    b.Property<DateTime>("MemTelTime1")
                        .HasColumnType("datetime")
                        .HasColumnName("Mem_TelTime1");

                    b.Property<DateTime>("MemTelTime2")
                        .HasColumnType("datetime")
                        .HasColumnName("Mem_TelTime2");

                    b.HasKey("MemSignQaid")
                        .HasName("PK__Mem_Sign__5DC3E46BF2F8F753");

                    b.HasIndex("MemSid");

                    b.ToTable("Mem_Sign");
                });

            modelBuilder.Entity("long_term_care.Models.MemberInformation", b =>
                {
                    b.Property<string>("MemSid")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SID");

                    b.Property<string>("MemAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Mem_Address");

                    b.Property<string>("MemBd")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Mem_BD");

                    b.Property<string>("MemCert")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_Cert");

                    b.Property<string>("MemEdu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_Edu");

                    b.Property<string>("MemExpr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_Expr");

                    b.Property<string>("MemGender")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_Gender");

                    b.Property<string>("MemIdent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_Ident");

                    b.Property<string>("MemMovt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Mem_Movt");

                    b.Property<string>("MemMphone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Mem_MPhone");

                    b.Property<string>("MemName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Mem_Name");

                    b.Property<string>("MemPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Mem_Password");

                    b.Property<string>("MemProf")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_Prof");

                    b.Property<string>("MemPserv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_PServ");

                    b.Property<string>("MemSerRec")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Mem_SerRec");

                    b.Property<string>("MemSite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Mem_Site");

                    b.Property<string>("MemTphone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("Mem_Tphone");

                    b.Property<string>("MemTrans")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_Trans");

                    b.Property<string>("MemUid")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Mem_UID");

                    b.Property<string>("MemUnitName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Mem_UnitName");

                    b.Property<string>("MemUnitNum")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_UnitNum");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemSid")
                        .HasName("PK__Member_I__47D0834AC937CAE3");

                    b.ToTable("Member_Information");
                });

            modelBuilder.Entity("long_term_care.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("long_term_care.Models.CarPick", b =>
                {
                    b.HasOne("long_term_care.Models.MemberInformation", "MemS")
                        .WithMany("CarPicks")
                        .HasForeignKey("MemSid")
                        .HasConstraintName("FK__car_pick__Mem_SI__44FF419A")
                        .IsRequired();

                    b.Navigation("MemS");
                });

            modelBuilder.Entity("long_term_care.Models.CaseActContent", b =>
                {
                    b.HasOne("long_term_care.Models.CaseAct", "Act")
                        .WithMany("CaseActContents")
                        .HasForeignKey("ActId")
                        .HasConstraintName("FK__Case_Act___Act_I__498EEC8D")
                        .IsRequired();

                    b.HasOne("long_term_care.Models.CaseInfor", "CaseNoNavigation")
                        .WithMany("CaseActContents")
                        .HasForeignKey("CaseNo")
                        .HasConstraintName("FK__Case_Act___Case___4A8310C6")
                        .IsRequired();

                    b.Navigation("Act");

                    b.Navigation("CaseNoNavigation");
                });

            modelBuilder.Entity("long_term_care.Models.CaseCareRecord", b =>
                {
                    b.HasOne("long_term_care.Models.CaseInfor", "CaseNoNavigation")
                        .WithMany("CaseCareRecords")
                        .HasForeignKey("CaseNo")
                        .HasConstraintName("FK__Case_Care__Case___29221CFB")
                        .IsRequired();

                    b.HasOne("long_term_care.Models.MemberInformation", "MemS")
                        .WithMany("CaseCareRecords")
                        .HasForeignKey("MemSid")
                        .HasConstraintName("FK__Case_Care__Mem_S__2A164134")
                        .IsRequired();

                    b.Navigation("CaseNoNavigation");

                    b.Navigation("MemS");
                });

            modelBuilder.Entity("long_term_care.Models.CaseDailyRegistration", b =>
                {
                    b.HasOne("long_term_care.Models.CaseInfor", "CaseNoNavigation")
                        .WithMany("CaseDailyRegistrations")
                        .HasForeignKey("CaseNo")
                        .HasConstraintName("FK__case_dail__Case___32E0915F")
                        .IsRequired();

                    b.Navigation("CaseNoNavigation");
                });

            modelBuilder.Entity("long_term_care.Models.CaseNeed", b =>
                {
                    b.HasOne("long_term_care.Models.CaseInfor", "CaseNoNavigation")
                        .WithMany("CaseNeeds")
                        .HasForeignKey("CaseNo")
                        .HasConstraintName("FK__Case_Need__Case___36B12243")
                        .IsRequired();

                    b.Navigation("CaseNoNavigation");
                });

            modelBuilder.Entity("long_term_care.Models.CasePhysicalMental", b =>
                {
                    b.HasOne("long_term_care.Models.CaseInfor", "CaseNoNavigation")
                        .WithMany("CasePhysicalMentals")
                        .HasForeignKey("CaseNo")
                        .HasConstraintName("FK__case_phys__Case___2CF2ADDF")
                        .IsRequired();

                    b.Navigation("CaseNoNavigation");
                });

            modelBuilder.Entity("long_term_care.Models.CaseTelRecord", b =>
                {
                    b.HasOne("long_term_care.Models.CaseInfor", "CaseNoNavigation")
                        .WithMany("CaseTelRecords")
                        .HasForeignKey("CaseNo")
                        .HasConstraintName("FK__Case_Tel___Case___2FCF1A8A")
                        .IsRequired();

                    b.HasOne("long_term_care.Models.MemberInformation", "MemS")
                        .WithMany("CaseTelRecords")
                        .HasForeignKey("MemSid")
                        .HasConstraintName("FK__Case_Tel___Mem_S__30C33EC3")
                        .IsRequired();

                    b.Navigation("CaseNoNavigation");

                    b.Navigation("MemS");
                });

            modelBuilder.Entity("long_term_care.Models.LectureTable", b =>
                {
                    b.HasOne("long_term_care.Models.MemberInformation", "MemS")
                        .WithMany("LectureTables")
                        .HasForeignKey("MemSid")
                        .HasConstraintName("FK__lecture_t__Mem_S__4222D4EF")
                        .IsRequired();

                    b.Navigation("MemS");
                });

            modelBuilder.Entity("long_term_care.Models.MemSign", b =>
                {
                    b.HasOne("long_term_care.Models.MemberInformation", "MemS")
                        .WithMany("MemSigns")
                        .HasForeignKey("MemSid")
                        .HasConstraintName("FK__Mem_Sign__Mem_SI__339FAB6E")
                        .IsRequired();

                    b.Navigation("MemS");
                });

            modelBuilder.Entity("long_term_care.Models.CaseAct", b =>
                {
                    b.Navigation("CaseActContents");
                });

            modelBuilder.Entity("long_term_care.Models.CaseInfor", b =>
                {
                    b.Navigation("CaseActContents");

                    b.Navigation("CaseCareRecords");

                    b.Navigation("CaseDailyRegistrations");

                    b.Navigation("CaseNeeds");

                    b.Navigation("CasePhysicalMentals");

                    b.Navigation("CaseTelRecords");
                });

            modelBuilder.Entity("long_term_care.Models.MemberInformation", b =>
                {
                    b.Navigation("CarPicks");

                    b.Navigation("CaseCareRecords");

                    b.Navigation("CaseTelRecords");

                    b.Navigation("LectureTables");

                    b.Navigation("MemSigns");
                });
#pragma warning restore 612, 618
        }
    }
}
